version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=myaccount
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=visitordb
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - 5431:5431

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080